version: '2'
services:
    productmasterapp-app:
        image: productmasterapp
        external_links:
            - productmasterapp-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=ProductMasterApp
            - SPRING_DATA_MONGODB_HOST=mongodb
        ports:
            - 8080:8080
    productmasterapp-mongodb:
        extends:
            file: mongodb.yml
            service: productmasterapp-mongodb
